# Generated by Django 5.0.2 on 2024-02-23 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
        ('reserva', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='dt_final',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dt_inicial',
            field=models.DateField(verbose_name='Data inicial'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='idquarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quarto.quarto', verbose_name='Quarto'),
        ),
    ]
